### ISSUE TITLE
forEach requires type parameter

### ISSUE THREAD

**Issue by AndrewSouthpaw** [ramda/types#112]
If I use `forEach` like so:

```ts
const nums: number[] = [1, 2, 3];
forEach((num) => {
  num + 1;
}, nums);
```

I'll get this error:

```
TS18046: num is of type unknown
```

I have to specify a type on the parameter, either by `forEach<number, number[]>` or in the cb as `forEach((num: number) => {})`.

It is able to tell when I supply it an invalid type, e.g. `num: string`.

It seems like it should be able to infer the type without extra guidance?

**Comment by Harris-Miller** [comment]
Oof! Yeah the current typing removed type inference for inline functions like that. That was unintentional from https://github.com/ramda/types/pull/19. The fix is easy, fortunately. See this playground link for a full explanation: https://tsplay.dev/Wkq71N. I'll have up an MR here in a bit

**Comment by AndrewSouthpaw** [comment]
Wow, the full explanation was _super_ helpful, thanks for putting that together! I learned something new about TS today. 😄  Specifically the Q&A at the end about "why not use the simpler version", I was wondering at exact question and you anticipated it.

Hopefully at some point I can get up to speed enough to start contributing to this libdef! I use ramda every day and love it to pieces, and wrangling the types can always prove quite difficult.
