### ISSUE TITLE
TS: Incorrect signature of R.values

### ISSUE THREAD

**Issue by lisumio** [ramda/types#119]
_Assumption:_ Calling `values` method with `null` works by design and not by mistake (returns `[]`). 

`R.values` expects input `obj` to be a `T` generic that extends `object` , but this produces following error when passing nullable type: 

`Type 'null' is not assignable to type 'object'`

PS. After checking https://github.com/ramda/ramda/issues/3264 and seeing that https://github.com/ramda/types/issues/118 is left open I've decided to post this issue here rather than in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) - hope it's alright.

**Comment by Harris-Miller** [comment]
`R.values()` rejects `null` same as `Object.values`. See here for example: https://tsplay.dev/WY5AxW

I believe the current implementation is correct. Closing
