### ISSUE TITLE
Typescript error for R.type when using a date type

### ISSUE THREAD

**Issue by azigoldstein** [ramda/types#120]
For typescript, when using the function R.type, the possible types are 
`"Object" | "Number" | "Boolean" | "String" | "Null" | "Array" | "RegExp" | "Function" | "Undefined" | "Symbol" | "Error"`

However, if you pass R.type(new Date ()), a string of 'Date' gets returned

**Comment by Harris-Miller** [comment]
`R.type` has since been updated to support all the types mentioned by OP and more. Closing
