### ISSUE TITLE
Export isNotEmpty types as it is now part of ramda 0.30.0

### ISSUE THREAD

**Issue by saksham-sharma** [ramda/types#123]
Can we please export the new types required for isNotEmpty? I see that a PR is open for it but not yet merged (https://github.com/ramda/types/pull/101). Unfortunately ramda-adjunct has upgraded their release to now import isNotEmpty from ramda which has the unfortunate consequence of breaking builds.

ramda changelog: https://github.com/ramda/ramda/issues/3453

**Comment by Harris-Miller** [comment]
`types-ramda@0.30.0` and `@types/ramda@0.30.0` have been released
