### ISSUE TITLE
mergeDeepLeft behaves differently than in @types/ramda

### ISSUE THREAD

**Issue by sandrosc** [ramda/types#17]
The following example has stopped working, since @types/ramda uses ramda-types:

```ts
import { mergeDeepLeft } from "ramda";

const translations = [
  { lang: "de", contact: { email: "moo@example.com", emailLabel: "E-Mail" } },
  { lang: "en", contact: { emailLabel: "Email" } }
];

function merge<T extends { lang: string }>(arr: T[]) {
  return mergeDeepLeft(arr[0], arr[1]) as T;
}

merge(translations);
```

Error message:
```
Conversion of type 'Assign<T, [T], "deep", BuiltIn, undefined>' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'Assign<T, [T], "deep", BuiltIn, undefined>'.ts(2352)
```

Please ignore in case this was done intentionally.

**Comment by Harris-Miller** [comment]
Not done intentionally. `ts-toolbelt` is used under the hood for types like this, and a Major version of that library happened with the migration over to `types-ramda`.

This behavior still works as expected
```typescript
type Foobar = { foo: { bar: string } };

const obj1: Foobar = { foo: { bar: 'hello' } };
const obj2: Foobar = { foo: { bar: 'world' } };

const r: Foobar = mergeDeepLeft(obj1, obj2);
```

While not ideal, you can get around your issue by doing `as unknown as T`
```typescript
function merge<T extends { lang: string }>(arr: T[]) {
  return mergeDeepLeft(arr[0], arr[1]) as unknown as T;
}
```

See this typescript playground for more details: https://tsplay.dev/mA8zQN

Will look into it is worth wrapping our own for this instead of relying on `ts-toolbelt`

**Comment by sandrosc** [comment]
> While not ideal, you can get around your issue by doing `as unknown as T`

That's what I ended up doing, thanks for the elaborate answer :).

**Comment by Harris-Miller** [comment]
@sandrosc while investigating how to fix this, I found quite a bit wrong with `O.Assign` for both shallow and deep merges. I took a crack at fixing them and found myself writing my own types to replace `O.Assign`

It does fix your specific issue, check out the MR: https://github.com/ramda/types/pull/18
