### ISSUE TITLE
`pluck` does not work with argument typed as `any`

### ISSUE THREAD

**Issue by ericyd** [ramda/types#34]
## Summary

When `pluck` is called with a final argument typed as `any`, it results in a TypeScript error.

I'm not sure if this is actually an error or desired behavior. Casting the argument to `any[]` resolves the type error. I would expect `any` to be allowed since it _can_ be a list, but perhaps that is not the intention of this lib. Of course, if this is desired behavior, please close

## Dependencies

- `ramda@0.29.0`
- `@types/ramda@0.29.1`
- `typescript@5.0.2`

## Example

- [Link to codesandbox](https://codesandbox.io/s/ramda-plucking-from-any-ikp1j6)

```typescript
import { pluck } from "ramda";

const array = [{ id: 1 }, { id: 2 }] as any;

pluck("id", array);
      ^^^^
```

## Error message (snippet)

```
No overload matches this call.
  Overload 1 of 4, '(p: never, list: readonly unknown[]): never[]', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'never'.
  Overload 2 of 4, '(p: number, list: { [k: number]: unknown; }[]): unknown[]', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'number'.
```

**Comment by Harris-Miller** [comment]
It is the desired behavior. For `pluck` to determine the values of a given key for an array of objects, we must constrain those array of objects to be **an array of objects**

We do need to better support objects and Functors, but the typings for arrays are correct as is

**Comment by ericyd** [comment]
I can see the logic in that. Thanks for the reply and all your work on this lib!
