### ISSUE TITLE
"AsyncFunction" is not listed in return type of type() 

### ISSUE THREAD

**Issue by Patriksafar** [ramda/types#57]
There is missing return type for `AsyncFunction`.

![Snímek obrazovky 2023-07-13 v 12 47 53](https://github.com/ramda/types/assets/36009266/723d7118-7160-4804-a299-9215518597fd)

https://github.com/ramda/types/blob/develop/types/type.d.ts

```ts
export function type(
  val: any,
):
| 'Object'
| 'Number'
| 'Boolean'
| 'String'
| 'Null'
| 'Array'
| 'RegExp'
| 'Function'
| 'Undefined'
| 'Symbol'
| 'Error'
| 'Date'
| 'AsyncFunction' // this is missing
```

**Comment by Harris-Miller** [comment]
https://github.com/ramda/types/pull/58
