### ISSUE TITLE
Type inference on ifElse

### ISSUE THREAD

**Issue by capArturo507** [ramda/types#59]
Hello , just wanted to leave this here, the type inference of the ifElse function seems to not be working in this case:  

![image](https://github.com/ramda/ramda/assets/9748621/71635e8b-a2c8-49dc-9284-c288f33c863c)

Bests!

**Comment by Harris-Miller** [comment]
`isNotNull` can remove `null | undefined` from a type, but it cannot infer that the incoming generic is `T | null | undefined`
You can set the generic yourself though on the function pointer `isNotNil<string | null>`

Playground link with full example: https://tsplay.dev/WyzJdw

**Comment by capArturo507** [comment]
Did not know I can pass types to Ramda functions great! thanks a lot for it.
