### ISSUE TITLE
Automate release

### ISSUE THREAD

**Issue by Harris-Miller** [ramda/types#7]
Currently, I'm just using `npm publish` on my local machine. I'd much rather move to a gitflow style with ` develop` and `main` branch. `semantic-release` I like a lot, as it gives us great control of automatic semver bumps and Github release info

Open to other suggestions as well. I just want to define what that process should be and come up with a good strategy in general

**Comment by davidchambers** [comment]
[xyz][1] is another option. Ramda uses it, as do many other projects. :)


[1]: https://github.com/davidchambers/xyz

**Comment by Harris-Miller** [comment]
Decided that automation is not worth it. This repo will hopefully be short to live anyhow. Will reopen the discussion if that ever changes
