### ISSUE TITLE
Make `isNotNil` a type guard

### ISSUE THREAD

**Issue by lensbart** [ramda/types#82]
Currently if you use `isNotNil` to filter an array of type `(T | undefined | null)[]`, the result will have the same type.

If, instead, we would define `isNotNil` as follows:
```ts
export const isNotNil = <T>(value?: T): value is Exclude<T, null | undefined> => value != null
```
we could do something like
```ts
const example = [1, 23, null, 5, undefined].filter(isNotNil) // typed as `number[]`
```

**Comment by Harris-Miller** [comment]
What you're asking for is the current behavior, see here: https://github.com/ramda/types/blob/develop/types/isNotNil.d.ts#L1
