### ISSUE TITLE
Why is `ElementOf` so complex?

### ISSUE THREAD

**Issue by rbuckton** [ramda/types#97]
What benefit does `ElementOf<T>` have over `T[number]`? The conditional type and use of `infer` are potentially far more expensive than is necessary.

**Comment by Harris-Miller** [comment]
TBH I stole that from here: https://github.com/ts-essentials/ts-essentials/blob/master/lib/element-of/index.ts#L1.

While `ts-toolbelt` is dependency already, it does not have a type function equivalent of `ElementOf`. I use `ts-essentials` at my job so was familiar with it, but I didn't want to add a new dependency for a single function so I just copy/pasted it.

You're right though, `T[number]` yields the same results and less expensive. Thanks for the tip!
